# Generated by Django 5.1.2 on 2024-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('fruit_id', models.AutoField(primary_key=True, serialize=False)),
                ('fruit_name', models.CharField(max_length=200)),
                ('fruit_price', models.IntegerField(max_length=10)),
                ('fruit_image', models.ImageField(upload_to='fruits')),
            ],
        ),
    ]
